### ISSUE TITLE
Do we have some forest-light scheme?

### ISSUE THREAD

**Issue by aasutossh** [sainnhe/forest-night#17]

**Comment by sainnhe** [comment]
No.

To be honest, I've tried 3 times to design a light variant for this color scheme, but never get a satisfactory result. I gave up.

I'm going to use gruvbox-material light if I want to use a light color scheme.

**Comment by aasutossh** [comment]
Same, forest-night is awesome, so is gruvbox-material.

**Comment by aasutossh** [comment]
@sainnhe is there a quick way to change colorscheme with keybinds?
I am looking at https://jnrowe.github.io/articles/tips/Toggling_settings_in_vim.html, but can't check for 
```
if colorscheme == "forest-night"
```

**Comment by sainnhe** [comment]
I prefer to use command to switch between color schemes: [init.vim](https://github.com/sainnhe/dotfiles/blob/f01703c8925334f70ec79603ee677448de614a5f/.config/nvim/init.vim#L907-L1016)

**Comment by aasutossh** [comment]
I guess I'll just copy that portion then.

**Comment by sainnhe** [comment]
I just designed a light variant based on solarized, you can update this color scheme and get it a try.

**Comment by aasutossh** [comment]
That's awesome.
