### ISSUE TITLE
Statement on maintenance

### ISSUE THREAD

**Issue by sainnhe** [sainnhe/forest-night#19]
Due to some personal reasons [gruvbox-material#23](https://github.com/sainnhe/gruvbox-material/issues/23#issue-570392877), I'll stop maintaining this project for a period of time(maybe about half a year).

This does not mean that this project has been abandoned, issues and PRs are welcome, I'll review them in the future.

If you're interested in this project and would like to become a maintainer, please [contact me](mailto:sainnhe@gmail.com).

Thanks for your understanding :)

**Comment by jef** [comment]
I'd love to see this with IntelliJ. I'll see if I can make something up in some spare time. Maybe we can create an org for it.

**Comment by sainnhe** [comment]
This project is now maintained by @jef .
