### ISSUE TITLE
refactor: JetBrains base

### ISSUE THREAD

**Issue by jef** [sainnhe/forest-night#28]
### Description

Move from Nord base to Gruvbox base to be consistent with theme.

### Possible solution

From @sainnhe:

> ...This color scheme is designed to be warm and soft, its main colors are red, orange, yellow and green. The current syntax highlighting is based on gruvbox-material which is inspired by gruvbox, its highlighting logic exactly coincides with the design. So I think maybe you can consider changing the highlight logic part of jetbrains to gruvbox based.
>
> https://plugins.jetbrains.com/plugin/12310-gruvbox-theme

**Comment by mhanberg** [comment]
Hi @jef, I am a big fan of this theme, thank you for stepping up as a maintainer!

Can you elaborate what you mean by "to be consistent with theme"?

**Comment by mhanberg** [comment]
Oh, I realize now you are referring to the JetBrains theme, specifically. Please disregard my previous comment if that is true 😅.

**Comment by jef** [comment]
Closed in favor of https://github.com/jef/forest-night-jetbrains/issues/1
