### ISSUE TITLE
feat: Xresources file?

### ISSUE THREAD

**Issue by ngynLk** [sainnhe/forest-night#32]
Would it be possible to have a `.Xresources` with this color palette?

I really like this colorscheme and a terminal colorscheme would be amazing I think.

**Comment by jef** [comment]
Sure, I can cook something up!

**Comment by jef** [comment]
Done!

- [jef/forest-night-xresources](https://github.com/jef/forest-night-xresources)
- Updated [wiki](https://github.com/sainnhe/forest-night/wiki/Related-Projects/7047f8ca721c4ac74fe0ae501ce2ddcce996f5a5)
