### ISSUE TITLE
bug: Background color is different ( bluish ) 

### ISSUE THREAD

**Issue by HARSH-SHETH** [sainnhe/forest-night#33]
### Problem

I installed the colorscheme and when I set the colorscheme to forest-night in my vimrc and source the file the background color do not match with the image in the readme.md. 
Also the color contrast is low as compared to the colors in the image from readme.md file
![night-forest](https://user-images.githubusercontent.com/43717513/86098267-83c7da00-bad3-11ea-96c4-fda587ffe784.png)

**Comment by sainnhe** [comment]
I think it's expected behavior, the background color in your screenshot is the same as the screenshot.

![](https://user-images.githubusercontent.com/37491630/74209833-5217b900-4c81-11ea-86e2-3727fdfc3233.png)

But the background color in the right side of your screenshot is a little bit bright, do you mean that should be fixed?

**Comment by ghifarit53** [comment]
hi @HARSH-SHETH, i'm the person you asked earlier on r/unixporn

So i've downloaded your screenshot, downloaded the screenshot in README, and try to compare it with my vim setup, here's the picture

![2020-06-30 at 15 18 12](https://user-images.githubusercontent.com/59758342/86101811-fc836200-bae4-11ea-8705-ff9129fbb1e4.png)

So the background are actually the same, and when i try to put the background color in color picker
![2020-06-30 at 15 07 43](https://user-images.githubusercontent.com/59758342/86101198-1d978300-bae4-11ea-9e44-11861a0f3c25.png)

it's actually not green at all, but rather blue or bluish, like you said

**Comment by HARSH-SHETH** [comment]
Ok I think I missjudge the colors in the reddit post I came across. Sorry for wasting your time

**Comment by jef** [comment]
> reddit post I came across

Which post are you talking about by chance @HARSH-SHETH?

**Comment by sainnhe** [comment]
This great [rice](https://www.reddit.com/r/unixporn/comments/hi0zmp/bspwm_green_tea_setup/) by @ghifarit53
