### ISSUE TITLE
feat: forest-day colorscheme?

### ISSUE THREAD

**Issue by loki7990** [sainnhe/forest-night#34]
### Description

Would it be possible to create a light variant that could be called forest-day?

### Possible solution

Easy mode would be to swap the background and foreground, but the colors in between would likely need to be slightly darker

**Comment by jef** [comment]
Cool idea! I'd leave this one up to @sainnhe to comment on what it would look like or if he had anything planned.

I'm interested of what it would look like just switching those two out -- if it would be still readable.

**Comment by loki7990** [comment]
Oh woops, just found #17 . I'll go ahead and close this, but feel free to reopen if this is a possibility

**Comment by sainnhe** [comment]
I just designed a light variant based on solarized, you can update this color scheme and get it a try.

**Comment by Barbarossa93** [comment]
It's gorgeous! Thank you!

**Comment by sainnhe** [comment]
@Barbarossa93 See /autoload/forest_night.vim .
