### ISSUE TITLE
Removing the comment highlighting

### ISSUE THREAD

**Issue by alt-romes** [sainnhe/forest-night#39]
Hello! I'm sure this is a problem on my side, but how could I edit the code for this "error" to go away?
I don't have experience with vim colorschemes so I thought it would be easier to ask for guidance.

This is what I currently have using iTerm2 in MacOS:
![Screenshot 2021-02-11 at 17 34 58](https://user-images.githubusercontent.com/21295306/107676288-dcc63600-6c90-11eb-9453-3347377658a4.png)

I would like to just have normal grey text characters without highlighting

Thank you,
~romes

**Comment by sainnhe** [comment]
See this:

https://github.com/sainnhe/forest-night/blob/170886eafc8a7606f1769d5313ed8b6044a67ce4/doc/forest-night.txt#L163-L177
